baseURL = 'https://skill3472.github.io/'
languageCode = 'en-us'
title = 'Maksymilian "Skill" Tym'
theme = 'hermit-master'
enableEmoji = true

[author]
    name = 'Maksymilian Tym'

[params]
    homeSubtitle = 'A computer person'

    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"

    code_copy_button = true


[[params.social]]
    name = 'github'
    url = 'https://github.com/skill3472'

[[params.social]]
    name = 'twitter'
    url = 'https://twitter.com/skill347'

[[params.social]]
    name = 'instagram'
    url = 'https://www.instagram.com/skill347_dev/'

[[params.social]]
    name = 'stackoverflow'
    url = 'https://stackoverflow.com/users/12069665/skill347'

[[params.social]]
    name = 'twitch'
    url = 'https://twitch.tv/skill347'

[[params.social]]
    name = 'itch'
    url = 'https://skill347.itch.io/'

[menu]

[[menu.main]]
    name = 'About me'
    url = 'about/'
    weight = 10

[[menu.main]]
    name = 'Posts'
    url = 'posts/'
    weight = 15

[[menu.main]]
    name = 'Donate'
    url = 'donate/'
    weight = 20
